replicaCount: 1

namespace: nodejs-rest-api

image:
  repository: ghcr.io/kesha123/nodejs-rest-api/api
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: nodejs-rest-api.innokentii-kozlov.com
  tls:
    enabled: true
    secretName: nodejs-rest-api-tls

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 300m
    memory: 256Mi

migrations:
  image:
    repository: ghcr.io/kesha123/nodejs-rest-api/migrations
    tag: latest
  envSecretName: postgres-credentials
  sslSecretName: migrations-ssl-certs

postgres:
  clusterName: postgres-cluster
  image:
    repository: ghcr.io/cloudnative-pg/cloudnative-pg
    tag: 1.26.0
  storage:
    size: 2Gi
    storageClass: standard
  replicaCount: 2
