replicaCount: 1

namespace: nodejs-rest-api
name: nodejs-rest-api

api:
  image:
    repository: ghcr.io/kesha123/nodejs-rest-api/api
    tag: 8d5f6b1e15bfb53f32a96a3ebf8af777047c35f5
  name: api

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: nodejs-rest-api.innokentii-kozlov.com
  tls:
    enabled: true
    secretName: nodejs-rest-api-tls

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 300m
    memory: 256Mi

migrations:
  image:
    repository: ghcr.io/kesha123/nodejs-rest-api/migrations
    tag: 8d5f6b1e15bfb53f32a96a3ebf8af777047c35f5
  name: migrations

postgres:
  clusterName: postgres-cluster
  image:
    repository: ghcr.io/cloudnative-pg/postgresql
    tag: 17.5
  storage:
    size: 2Gi
    storageClass: standard
  replicaCount: 2
