version: '3.8'

services:
  postgres-database:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres-database
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - nodejs-rest-api
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-database:5432/${POSTGRES_DB}
    ports:
      - "3000:3000"
    depends_on:
      - postgres-database
    networks:
      - nodejs-rest-api

volumes:
  postgres_data:

networks:
  nodejs-rest-api:
    driver: bridge
