version: "3.8"


services:
  postgres:
    image: ghcr.io/kesha123/nodejs-rest-api/postgres:${DATABASE_IMAGE_TAG:-latest}
    container_name: postgres
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    env_file:
      - .env
    volumes:
      - ./ssl/server.crt:/var/lib/postgresql/server.crt:ro
      - ./ssl/server.key:/var/lib/postgresql/server.key:ro
      - ../sql/insert.sql:/opt/sql/insert.sql:ro
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nodejs-rest-api
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: ghcr.io/kesha123/nodejs-rest-api/migrations:${MIGRATIONS_IMAGE_TAG:-latest}
    env_file:
      - .env
    depends_on:
      - postgres


networks:
  nodejs-rest-api:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16


volumes:
  postgres_data:
    driver: local
