version: "3.8"


services:
  nginx-proxy:
    image: nginx:${NGINX_PROXY_IMAGE_TAG:-stable-alpine3.21}
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nodejs-rest-api
    ports:
      - 8080:80
      - 4430:443
    depends_on:
      - api

  api:
    image: ghcr.io/kesha123/nodejs-rest-api/api:${API_IMAGE_TAG:-latest}
    container_name: api
    volumes:
      - .ssl/ca.crt:/app/ssl/ca.crt:ro
      # - ./ssl/privkey.pem:/app/ssl/privkey.pem
      # - ./ssl/server.crt:/app/ssl/server.crt
      # - ./ssl/server.key.bak:/app/ssl/server.key
    env_file:
      - .env
    networks:
      - nodejs-rest-api

networks:
  nodejs-rest-api:
    driver: bridge
