{{ if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-route53
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: innokentiikozlov@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-route53-account-key
    solvers:
    - dns01:
        route53:
          region: eu-north-1
          hostedZoneID: Z07266063B6JW9NSLBQB
          accessKeyID: AKIA6GBMBTPR34OLN65X
          secretAccessKeySecretRef:
            name: route53-credentials
            key: secret-access-key
{{ end }}
