apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}-deployment
  namespace: {{ .Values.namespace | default "nodejs-rest-api" }}
  labels:
    app: {{ .Values.api.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      containers:
        - name: {{ .Values.api.name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
          - containerPort: 3000
          env:
          - name: API_PORT
            value: "3000"
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: port
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: dbname
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-ssl
              mountPath: /app/ssl
              readOnly: true
      volumes:
        - name: postgres-ssl
          projected:
            sources:
              - secret:
                  name: postgres-cluster-ca
                  items:
                    - key: ca.crt
                      path: ca.crt
              - secret:
                  name: postgres-cluster-server
                  items:
                    - key: tls.crt
                      path: server.crt
                    - key: tls.key
                      path: server.key
