apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.api.name }}-migrations
  namespace: {{ .Values.namespace | default "nodejs-rest-api" }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ .Values.api.name }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: {{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}
          env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: port
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-cluster-app
                key: dbname
          volumeMounts:
          - name: postgres-ssl
            mountPath: /migrations/ssl
            readOnly: true
      volumes:
        - name: postgres-ssl
          projected:
            sources:
              - secret:
                  name: postgres-cluster-ca
                  items:
                    - key: ca.crt
                      path: ca.crt
