apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.name }}-seed-sql
  namespace: {{ .Values.namespace | default "nodejs-rest-api" }}
  labels:
    app: {{ .Values.api.name }}
data:
  insert.sql: |-
{{ (.Files.Get "files/insert.sql") | indent 4 }}
