apiVersion: v1

kind: PersistentVolume

metadata:
  name: api-pv

spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standart
  hostPath:
    path: /data
    type: DirectoryOrCreate
