repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: traefik
    url: https://traefik.github.io/charts
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.18.1
    set:
      - name: installCRDs
        value: "true"
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: v36.1.0
  - name: cnpg
    namespace: cnpg-system
    chart: cnpg/cloudnative-pg
    version: v0.24.0
  - name: argo-cd
    namespace: argo-cd
    chart: argo/argo-cd
    version: 8.1.1
