name: API Build


on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      ".github/workflows/api/build.yaml"


concurrency:
  group: ${{  github.workflow }}-api-build
  cancel-in-progress: false


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: dist/
