name: Production Deploy


on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      TAG:
        type: string
        required: true
        description: 'The associated tag for the Docker image'


env:
  HELM_PACKAGES_REPO: helm-packages


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-k8s-deployment
  cancel-in-progress: true


jobs:
  call-api-docker-build-push:
    name: Docker Build and Push
    uses: ./.github/workflows/api-docker-build-push.yaml
    secrets: inherit
    with:
      TAG: ${{ github.ref_name }}

  call-migrations-docker-build-push:
    name: Docker Build and Push
    uses: ./.github/workflows/migrations-docker-build-push.yaml
    secrets: inherit
    with:
      TAG: ${{ github.ref_name }}

  merge-json-outputs:
    name: Merge JSON Outputs
    runs-on: ubuntu-latest
    needs: [call-api-docker-build-push, call-migrations-docker-build-push]
    outputs:
      merged_images: ${{ steps.merge.outputs.merged_images }}
    steps:
      - name: Merge JSON Outputs
        id: merge
        run: |
          api_image=${{ needs.call-api-docker-build-push.outputs.image }}
          migrations_image=${{ needs.call-migrations-docker-build-push.outputs.image }}
          merged_images=$(jq -n --argjson api "$api_image" --argjson migrations "$migrations_image" '{api: $api.api, migrations: $migrations.migrations}')
          echo "merged_images=$merged_images" >> $GITHUB_ENV
          echo "::set-output name=merged_images::$merged_images"

  call-update-helm-package:
    name: Update Helm Package
    needs: merge-json-outputs
    uses: Kesha123/helm-packages/.github/workflows/update-helm-package.yaml@main
    secrets: inherit
    with:
      PROJECT_NAME: nodejs-rest-api
      TAG:  ${{ github.ref_name }}
      IMAGES: ${{ needs.merge-json-outputs.outputs.merged_images }}
