name: Production Deploy


on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      TAG:
        type: string
        required: true
        description: 'The associated tag for the Docker image'


env:
  HELM_PACKAGES_REPO: helm-packages


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-k8s-deployment
  cancel-in-progress: true


jobs:
  call-docker-build-push:
    name: Docker Build and Push
    uses: ./.github/workflows/docker-build-push.yaml
    secrets: inherit
    with:
      TAG: ${{ github.ref_name }}

  call-update-helm-package:
    name: Update Helm Package
    needs: call-docker-build-push
    uses: Kesha123/helm-packages/.github/workflows/update-helm-package.yaml@main
    secrets: inherit
    with:
      PROJECT_NAME: nodejs-rest-api
      TAG:  ${{ github.ref_name }}
      IMAGES: ${{ needs.call-docker-build-push.outputs.image }}
