name: Test - Api


on:
  workflow_call:
  push:
    branches:
      - main
    paths:
      ".github/workflows/api/test.yaml"


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .npmrc for multiple registries
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "@kesha123:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: npm test
