name: Test - datasource


on:
  workflow_call:


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
